[tool.poetry]
name = "transformer"
version = "0.1.0"
description = ""
authors = ["Aldo Costa <aldo.costa@web.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
